### ISSUE TITLE
Include `.apk` in Release

### ISSUE THREAD

**Issue by mickelsonmichael** [nikolajakshic/dagger#23]
The [Obtainium](https://github.com/ImranR98/Obtainium) app has a nice feature that will search GitHub releases for `.apk` files and allow apps to be managed and updated. It would be nice if the APKs could be included in future releases so Obtainium can be leveraged to easily install updates

**Comment by nikolajakshic** [comment]
A quick check showed that Obtainium does not support .aab files, which are already included. I will include APKs in future releases.

**Comment by nikolajakshic** [comment]
https://github.com/nikolajakshic/dagger/releases/tag/1.3.4
